### ISSUE TITLE
Jira backup stops due to a curl error

### ISSUE THREAD

**Issue by HendrikZA** [mattock/automatic-cloud-backup#15]
Hi, thanks for this awesome script with the new endpoints much appreciated! The Confluence backup works great but when I try to run the Jira backup with --source jira, I get this curl error thrown:

parse error: Invalid numeric literal at line 1, column 10
curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

I've checked all your curl statements and they seem fine to me. Can you please check if you get the same issue as me with the new changes in pull 14?

Thanks!

**Comment by bwegman** [comment]
Could you run the script using the statement `bash -x backup.sh`? This should give a dump of all the commands that bash is executing, including the curl one that is giving the error.

**Comment by dzschille** [comment]
@HendrikZA Have you tried the update in PR #14?

**Comment by HendrikZA** [comment]
Hi guys, thanks for the help. We managed to figure it out in the end. I wasn't getting a numerical value for the lasttaskid. So now I have that working and its all 100% :) Thanks again!

**Comment by robnoake** [comment]
The error we saw was related to `$LASTTASKID` which gets added in PR #13.

When @HendrikZA and I query `/rest/backup/1/export/lastTaskId` in our JIRA Cloud instance we were receiving an HTML 404 message back, which was then appended to the progress checking URL.

We're going to try reading the task ID out of the new endpoint described in https://jira.atlassian.com/browse/JRACLOUD-67169

I can't test that straight away as we've already got a JIRA backup underway. If it takes care of the issue I'll raise a PR tomorrow with our changes.

**Comment by dzschille** [comment]
@robnoake , @HendrikZA , have you both tried it with the branch new-endpoints which is PR #14? This is the needed change for https://jira.atlassian.com/browse/JRACLOUD-67169.

**Comment by kjaunslavietis** [comment]
@dzschille Hi, this is failing for me as well with the same errors using the endpoints from #14

**Comment by robnoake** [comment]
@dzschille Yes, we are testing with the updated backup endpoint.

Our sticking point is that the lastTaskId endpoint isn't present in Cloud
v1000.1218.0 - from JRACLOUD-67169 it looks like runbackup should return
the taskID for us.

I'll be testing a patch to grab the task ID out of runbackup and validate
it once our backup rate limit resets.

**Comment by dzschille** [comment]
Ah, okay. And thanks for testing!

Should i merge PR #14 into master? So it would be easier to make a new PR with a fix. Or should we point a new PR to the branch new-endpoints than? @mattock ?

**Comment by mattock** [comment]
@dzschille : I'll merge both PR https://github.com/mattock/automatic-cloud-backup/pull/14 and https://github.com/mattock/automatic-cloud-backup/pull/13 to make further development easier. Both look good to me, and the new dependency to [jq](https://stedolan.github.io/jq/) has been documented.

**Comment by dzschille** [comment]
@mattock Great, thanks!
